<?php
namespace Trustev\Entities;

/*
* This is the Trustev Decision object and contains the results of a Trustev Decision on a Case. 
*/
class DecisionBase
{

	/**
	 * This is the Id generated by the Trustev Platform
	 * @var string
	 */
	public $Id;

	/**
	 * @var number
	 */
	public $Version;

	/**
	 * The SessionId of the Case that this Decision was based on
	 * @var string
	 */
	public $SessionId;

	/**
	 * The Date Time that this Decision was generated at
	 * @var \DateTime
	 */
	public $Timestamp;

	/**
	 * @var string
	 */
	public $Type;

	/**
	 * The Result of the Trustev Decision.
	 * @var DecisionResultEnum
	 */
	public $Result;

	/**
	 * This is the score that Trustev assigned the Case. This can be ignored.
	 * @var number
	 */
	public $Score;

	/**
	 * A Trustev Confidence Score represents our confidence on a Trustev Decision based on the level of details supplied within a Trustev Case. 
	 * The Trustev Confidence Score is out of 100. 100 being all information was supplied and validated and 0 indicating that no information was contained within the Trustev Case.
	 * @var number
	 */
	public $Confidence;

	/**
	 * The Trustev Comment that Trustev has added to this Decision.
	 * @var string
	 */
	public $Comment;
	
}